#!/bin/bash

# Termux-LocalHost Installer
# Version: 2.0
# Author: Y-Nabeel
# GitHub: https://github.com/y-nabeelxd/Termux-LocalHost

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

find_available_port() {
    local port=$1
    while true; do
        if ! nc -z localhost "$port" &>/dev/null; then
            echo "$port"
            return
        fi
        ((port++))
    done
}

dir_exists() {
    if [ -d "$1" ]; then
        return 0
    else
        return 1
    fi
}

start_server() {
    local port=$(find_available_port "$LOCALHOST_PORT")
    local port_file="$HOME/.localhost_port"
    
    if ! nc -z localhost "$port" &>/dev/null; then
        if command -v termux-setup-storage &>/dev/null; then
            echo -e "${YELLOW}Attempting to open port $port...${NC}"
            termux-chroot -e echo "Opening port $port" || true
        fi
    fi
    
    php -S localhost:"$port" -t "$1" > /dev/null 2>&1 &
    
    echo "$port" > "$port_file"
    chmod 600 "$port_file"
    
    echo -e "${GREEN}Serving '${YELLOW}$1${GREEN}' on ${YELLOW}http://localhost:$port${NC}"
    echo -e "To stop the server, run: ${YELLOW}stoplocal${NC}"
}

stop_localhost() {
    local port_file="$HOME/.localhost_port"
    if [ -f "$port_file" ]; then
        local port=$(cat "$port_file")
        pkill -f "php -S localhost:$port"
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}Stopped localhost server on port ${YELLOW}$port${NC}"
            rm "$port_file"
        else
            echo -e "${RED}No localhost server found running on port ${YELLOW}$port${NC}"
        fi
    else
        echo -e "${RED}No localhost server found running (no port information available)${NC}"
        echo -e "You can try: ${YELLOW}pkill -f 'php -S localhost:'${NC}"
    fi
}

localhost() {
    if [ "$1" == "stop" ]; then
        stop_localhost
        return
    fi

    if [ -z "$1" ]; then
        echo -e "${RED}Error: Please provide directory path${NC}"
        echo -e "Usage: ${YELLOW}localhost [path]${NC}"
        echo -e "       ${YELLOW}localhost stop${NC}"
        return 1
    fi

    if ! dir_exists "$1"; then
        echo -e "${RED}Error: Directory '${YELLOW}$1${RED}' does not exist${NC}"
        return 1
    fi

    start_server "$1"
}

if [ -w "$PREFIX/bin" ]; then
    BIN_DIR="$PREFIX/bin"
elif [ -w "$HOME/bin" ]; then
    BIN_DIR="$HOME/bin"
    export PATH="$BIN_DIR:$PATH"
    echo -e "${YELLOW}Adding $BIN_DIR to PATH${NC}"
else
    echo -e "${RED}Neither $PREFIX/bin nor $HOME/bin are writable. Cannot proceed.${NC}"
    exit 1
fi

LOCALHOST_PORT="8080"

cat << EOF > "$BIN_DIR/localhost"
#!/bin/bash

# Do not edit manually - Generated by installer

port_file="\$HOME/.localhost_port"

find_available_port() {
    local port=\$1
    while true; do
        if ! nc -z localhost "\$port" &>/dev/null; then
            echo "\$port"
            return
        fi
        ((port++))
    done
}

dir_exists() {
    if [ -d "\$1" ]; then
        return 0
    else
        return 1
    fi
}

start_server() {
    local port=\$(find_available_port "$LOCALHOST_PORT")
    
    if ! nc -z localhost "\$port" &>/dev/null; then
        if command -v termux-setup-storage &>/dev/null; then
            echo -e "\033[1;33mAttempting to open port \$port...\033[0m"
            termux-chroot -e echo "Opening port \$port" || true
        fi
    fi
    
    php -S localhost:"\$port" -t "\$1" > /dev/null 2>&1 &
    echo "\$port" > "\$port_file"
    chmod 600 "\$port_file"
    
    echo -e "\033[0;32mServing '\033[1;33m\$1\033[0;32m' on \033[1;33mhttp://localhost:\$port\033[0m"
    echo -e "To stop the server, run: \033[1;33mstoplocal\033[0m"
}

stop_localhost() {
    if [ -f "\$port_file" ]; then
        local port=\$(cat "\$port_file")
        pkill -f "php -S localhost:\$port"
        if [ \$? -eq 0 ]; then
            echo -e "\033[0;32mStopped localhost server on port \033[1;33m\$port\033[0m"
            rm "\$port_file"
        else
            echo -e "\033[0;31mNo localhost server found running on port \033[1;33m\$port\033[0m"
        fi
    else
        echo -e "\033[0;31mNo localhost server found running (no port information available)\033[0m"
        echo -e "You can try: \033[1;33mpkill -f 'php -S localhost:'\033[0m"
    fi
}

if [ "\$1" == "stop" ]; then
    stop_localhost
    exit 0
fi

if [ -z "\$1" ]; then
    echo -e "\033[0;31mError: Please provide directory path\033[0m"
    echo -e "Usage: \033[1;33mlocalhost [path]\033[0m"
    echo -e "       \033[1;33mlocalhost stop\033[0m"
    exit 1
fi

if ! dir_exists "\$1"; then
    echo -e "\033[0;31mError: Directory '\033[1;33m\$1\033[0;31m' does not exist\033[0m"
    exit 1
fi

start_server "\$1"
EOF

chmod +x "$BIN_DIR/localhost"

if [ -f ~/.zshrc ]; then
    CONFIG_FILE=~/.zshrc
    PROFILE_FILE=~/.zprofile
else
    CONFIG_FILE=~/.bashrc
    PROFILE_FILE=~/.bash_profile
fi

if ! grep -q "alias stoplocal=" "$CONFIG_FILE"; then
    echo "alias stoplocal='localhost stop'" >> "$CONFIG_FILE"
fi

source "$CONFIG_FILE" >/dev/null 2>&1
echo "source $CONFIG_FILE" >> "$PROFILE_FILE"

clear
echo -e "${GREEN}╔════════════════════════════════════════╗"
echo -e "║   ${YELLOW}Termux-LocalHost Installation Complete${GREEN}   ║"
echo -e "╚════════════════════════════════════════╝${NC}"
echo -e "\n${YELLOW}Usage:${NC}"
echo -e "  ${GREEN}localhost [path]${NC}    # Start server for directory"
echo -e "  ${GREEN}stoplocal${NC}          # Stop running server"
echo -e "\n${YELLOW}Examples:${NC}"
echo -e "  ${GREEN}localhost ~/my-website${NC}"
echo -e "  ${GREEN}localhost /sdcard/my-project${NC}"
echo -e "\n${YELLOW}Note:${NC}"
echo -e "- Server starts on first available port from 8080"
echo -e "- Port information is stored in ~/.localhost_port"
echo -e "\n${YELLOW}Restart Termux or run:${NC} ${GREEN}source $CONFIG_FILE${NC}"
sleep 5
